// frontend/src/lib/components/Controls.svelte
<script lang="ts">
	import { addOrder, addBot, removeBot } from '$lib/websocket';
</script>

<div class="flex flex-wrap justify-center gap-3 p-4">
	<button
		onclick={() => addOrder('normal')}
		class="rounded-lg bg-[#DA291C] px-5 py-3 font-bold text-white shadow-lg transition-all hover:scale-105 hover:bg-[#b8221a] active:scale-95 cursor-pointer"
	>
		New Normal Order
	</button>
	<button
		onclick={() => addOrder('vip')}
		class="rounded-lg bg-[#FFC72C] px-5 py-3 font-bold text-[#27251F] shadow-lg transition-all hover:scale-105 hover:bg-[#e6b327] active:scale-95 cursor-pointer"
	>
		New VIP Order
	</button>
	<button
		onclick={() => addBot()}
		class="rounded-lg border-2 border-[#FFC72C] bg-transparent px-5 py-3 font-bold text-[#FFC72C] shadow-lg transition-all hover:scale-105 hover:bg-[#FFC72C] hover:text-[#27251F] active:scale-95 cursor-pointer"
	>
		+ Bot
	</button>
	<button
		onclick={() => removeBot()}
		class="rounded-lg border-2 border-[#DA291C] bg-transparent px-5 py-3 font-bold text-[#DA291C] shadow-lg transition-all hover:scale-105 hover:bg-[#DA291C] hover:text-white active:scale-95 cursor-pointer"
	>
		- Bot
	</button>
</div>

// src/components/Controls.tsx
interface ControlsProps {
  onNewNormal: () => void
  onNewVip: () => void
  onAddBot: () => void
  onRemoveBot: () => void
  botCount: number
}

export function Controls({
  onNewNormal,
  onNewVip,
  onAddBot,
  onRemoveBot,
  botCount,
}: ControlsProps) {
  const base =
    'rounded-md px-3.5 py-2 text-sm font-medium shadow-sm transition active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-40'
  const secondary = `${base} border border-slate-300 bg-white text-slate-700 hover:bg-slate-50`
  const primary = `${base} bg-slate-900 text-white hover:bg-slate-700`
  const vip = `${base} bg-amber-500 text-white hover:bg-amber-600`

  return (
    <div className="flex flex-wrap items-center gap-2">
      <button className={secondary} onClick={onNewNormal}>
        New Normal Order
      </button>
      <button className={vip} onClick={onNewVip}>
        New VIP Order
      </button>

      <span className="mx-1 h-6 w-px bg-slate-200" aria-hidden />

      <button className={primary} onClick={onAddBot}>
        Add Bot
      </button>
      <button className={secondary} onClick={onRemoveBot} disabled={botCount === 0}>
        Remove Bot
      </button>
    </div>
  )
}
