// src/components/Controls.vue
<template>
  <div class="flex flex-col gap-4">
    <Button @click="orderStore.addOrder('Normal')">Add Normal Order</Button>
    <Button @click="orderStore.addOrder('VIP')">Add VIP Order</Button>
    <Button @click="botStore.addBot">+ Bot</Button>
    <Button @click="botStore.removeBot" :disabled="!bots.length">- Bot</Button>
  </div>
</template>

<script setup lang="ts">
import { useBotStore } from '@/stores/bot'
import { useOrderStore } from '@/stores/order'
import { Button } from '@/components/ui/button'

const orderStore = useOrderStore()
const botStore = useBotStore()

const bots = botStore.bots
</script>

// src/components/controls.tsx
import { Button } from '@/components/ui/button';
import { useBots } from '@/store/use-order-controller';
import { controllerActions } from '@/store/use-order-controller';

export function Controls() {
  const bots = useBots();

  return (
    <div className="flex flex-wrap gap-2">
      <Button onClick={controllerActions.addNormalOrder}>New Normal Order</Button>
      <Button variant="secondary" onClick={controllerActions.addVipOrder}>
        New VIP Order
      </Button>
      <Button variant="outline" onClick={controllerActions.addBot}>
        + Bot
      </Button>
      {/* Disabled when no bots exist — prevents a confusing no-op */}
      <Button
        variant="destructive"
        onClick={controllerActions.removeBot}
        disabled={bots.length === 0}
      >
        - Bot
      </Button>
    </div>
  );
}
