// frontend/src/components/OrderList.tsx
import React from "react";
import { useOrderStore, type Order } from "../store/useOrderStore";

export const OrderList: React.FC = () => {
  const { vipQueue, normalQueue, orders } = useOrderStore();

  const pendingOrders = [...vipQueue, ...normalQueue]
    .map((id) => orders.find((o) => o.id === id))
    .filter((o): o is Order => o !== undefined);

  return (
    <div className="mb-6">
      <h2 className="text-lg font-semibold mb-2">PENDING</h2>
      <div className="flex flex-wrap gap-4 justify-center">
        {pendingOrders.map((order) => (
          <div
            key={order.id}
            className={`border p-4 rounded w-40 text-black ${
              order.type === "VIP" ? "bg-yellow-200" : "bg-gray-200"
            }`}
          >
            <div className="font-bold">{order.displayId}</div>
            <div>Type: {order.type}</div>
          </div>
        ))}
        {pendingOrders.length === 0 && <div>No pending orders</div>}
      </div>
    </div>
  );
};

// src/components/OrderList.vue
<template>
  <div class="h-64 border rounded bg-white shadow-md grid grid-cols-2 gap-4 p-4">
    <div>
      <p class="text-black font-bold">Pending Orders</p>
      <ul v-for="order in pendingOrders" :key="order.id">
        <OrderItem :id="order.id" :type="order.type" :status="order.status" />
      </ul>
    </div>
    <div>
      <p class="text-black font-bold">Completed Orders</p>
      <ul v-for="order in completedOrders" :key="order.id">
        <OrderItem :id="order.id" :type="order.type" :status="order.status" />
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useOrderStore } from '@/stores/order'
import { computed } from 'vue'
import OrderItem from './OrderItem.vue'

const orderStore = useOrderStore()
const orders = orderStore.orders

const pendingOrders = computed(() =>
  orders
    .filter((order) => order.status !== 'COMPLETED')
    .sort((a, b) => (a.type === 'VIP' && b.type !== 'VIP' ? -1 : 1)),
)
const completedOrders = computed(() => orders.filter((order) => order.status === 'COMPLETED'))
</script>
