// mekdi-frontend/src/components/order/OrderCard.vue
<script setup lang="ts">
import { Card } from '@/components/ui'
import { cn } from '@/lib/utils'
import type { OrderEntity } from '@/domains/order'
import { OrderType, OrderStatus } from '@/domains/order'

interface Props {
  order: OrderEntity
}

defineProps<Props>()
</script>

<template>
  <Card
    :class="cn(
      'p-4 flex items-center justify-between transition-all',
      order.type === OrderType.VIP && 'border-amber-400 bg-amber-50',
      order.status === OrderStatus.PROCESSING && 'ring-2 ring-blue-400 animate-pulse'
    )"
  >
    <div class="flex items-center gap-3">
      <span class="font-semibold text-lg">#{{ order.id }}</span>
      <span
        :class="cn(
          'px-2 py-1 rounded text-xs font-medium',
          order.type === OrderType.VIP
            ? 'bg-amber-200 text-amber-800'
            : 'bg-gray-200 text-gray-800'
        )"
      >
        {{ order.type }}
      </span>
    </div>
    <span
      :class="cn(
        'text-sm font-medium',
        order.status === OrderStatus.PENDING && 'text-yellow-600',
        order.status === OrderStatus.PROCESSING && 'text-blue-600',
        order.status === OrderStatus.COMPLETE && 'text-green-600'
      )"
    >
      {{ order.status }}
    </span>
  </Card>
</template>

// src/components/order-card.tsx
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { formatTime } from '@/core/format';
// No domain logic — just renders the data from a snapshot order.
import type { Order } from '@/core/types';

interface OrderCardProps {
  order: Order;
}

export function OrderCard({ order }: OrderCardProps) {
  return (
    <Card
      data-testid={
        order.status === 'PENDING'
          ? 'pending-card'
          : order.status === 'COMPLETE'
            ? 'complete-card'
            : 'processing-card'
      }
    >
      <CardContent className="flex items-center justify-between gap-2 py-3">
        <div className="flex items-center gap-2">
          <span className="text-sm font-mono font-semibold text-slate-700">#{order.id}</span>
          <Badge variant={order.type === 'VIP' ? 'vip' : 'default'}>{order.type}</Badge>
        </div>

        <div className="flex items-center gap-2">
          {order.status === 'COMPLETE' && (
            <span data-testid="completed-at" className="text-xs text-slate-500 font-mono">
              {formatTime(order.completedAt)}
            </span>
          )}
          <Badge
            variant={
              order.status === 'COMPLETE'
                ? 'complete'
                : order.status === 'PROCESSING'
                  ? 'processing'
                  : 'default'
            }
          >
            {order.status}
          </Badge>
        </div>
      </CardContent>
    </Card>
  );
}
