// client/src/components/OrderCard.tsx
import { Order } from '../types';

interface OrderCardProps {
  order: Order;
}

export function OrderCard({ order }: OrderCardProps) {
  const statusColors = {
    PENDING: 'bg-yellow-100 border-yellow-300',
    PROCESSING: 'bg-blue-100 border-blue-300',
    COMPLETE: 'bg-green-100 border-green-300',
  };

  const statusTextColors = {
    PENDING: 'text-yellow-800',
    PROCESSING: 'text-blue-800',
    COMPLETE: 'text-green-800',
  };

  const typeColors = {
    NORMAL: 'bg-gray-200 text-gray-800',
    VIP: 'bg-purple-200 text-purple-800',
  };

  return (
    <div className={`border-2 rounded-lg p-4 ${statusColors[order.status]}`}>
      <div className="flex justify-between items-start mb-2">
        <div className="font-bold text-2xl">Order #{order.id}</div>
        <span
          className={`px-3 py-1 rounded-full text-sm font-semibold ${typeColors[order.type]}`}
        >
          {order.type}
        </span>
      </div>
      <div className={`text-sm font-semibold ${statusTextColors[order.status]}`}>
        {order.status}
      </div>
      {order.completedAt && (
        <div className="mt-2 text-gray-600 text-xs">
          Completed: {new Date(order.completedAt).toLocaleTimeString()}
        </div>
      )}
    </div>
  );
}

// frontend/src/lib/components/OrderCard.svelte
<script lang="ts">
	import type { Order, Bot } from '$lib/types';

	let { order, bots = [] }: { order: Order; bots?: Bot[] } = $props();

	const statusLabels = ['PENDING', 'PROCESSING', 'COMPLETE'];
	const statusColors = ['text-yellow-400', 'text-orange-400', 'text-green-400'];

	let assignedBot = $derived(bots.find((b) => b.order?.id === order.id));
</script>

<div
	class="relative rounded-lg border bg-[#3a3733] p-3 shadow-md transition-all {order.type === 1
		? 'border-[#FFC72C]'
		: 'border-[#4a4843]'} {order.status === 1 ? 'animate-pulse' : ''}"
>
	<div class="mb-1 flex items-center justify-between">
		<span class="text-lg font-bold text-white">#{order.id}</span>
		{#if order.type === 1}
			<span class="rounded-full bg-[#FFC72C] px-2 py-0.5 text-xs font-bold text-[#27251F]"
				>VIP</span
			>
		{:else}
			<span class="rounded-full bg-[#4a4843] px-2 py-0.5 text-xs font-bold text-gray-300"
				>Normal</span
			>
		{/if}
	</div>
	<div class="text-sm {statusColors[order.status]}">
		{statusLabels[order.status]}
	</div>
	{#if assignedBot}
		<div class="mt-1 text-xs text-gray-400">Bot #{assignedBot.id}</div>
	{/if}
</div>
