// src/components/BotManager.vue
<template>
  <div>
    <h2>Bot List</h2>
    <ul>
      <li v-for="bot in bots" :key="bot.id">Bot #{{ bot.id }} - Status: {{ bot.status }}</li>
    </ul>
  </div>
  <button @click="botStore.addBot">Add Bot</button>
  <button :disabled="!bots.length" @click="botStore.removeBot">Remove Bot</button>
</template>

<script setup lang="ts">
import { useBotStore } from '@/stores/bot'

const botStore = useBotStore()
const bots = botStore.bots

bots.forEach((bot) => {
  if (bot.status === 'PROCESSING' && bot.currentOrderId) {
    bot.status = `PROCESSING Order #${bot.currentOrderId}`
  }
})
</script>

// mc-order-app/src/components/BotManager.jsx
import { useOrder } from '../store/OrderContext';

export default function BotManager() {
  const { state, addBot, removeBot } = useOrder();
  const isManager = state.role === 'manager';

  return (
    <div className="panel-section">
      <h3>机器人管理</h3>
      {isManager && (
        <div style={{ marginBottom: 12 }}>
          <button className="btn btn-add" onClick={addBot}>
            + Bot
          </button>
          <button
            className="btn btn-remove"
            onClick={removeBot}
            disabled={state.bots.length === 0}
          >
            - Bot
          </button>
        </div>
      )}
      <div className="bot-list">
        {state.bots.length === 0 ? (
          <div style={{ color: '#ccc', fontSize: 13, textAlign: 'center', padding: 8 }}>
            暂无机器人
          </div>
        ) : (
          state.bots.map(bot => (
            <div key={bot.id} className="bot-item">
              <span className={`bot-dot ${bot.status}`} />
              <span>
                机器人 #{bot.id}
                {bot.status === 'processing' && bot.currentOrder && (
                  <> — 处理中: 订单 #{bot.currentOrder.id} ({bot.currentOrder.type === 'vip' ? 'VIP' : 'Normal'})</>
                )}
                {bot.status === 'idle' && ' — 空闲'}
              </span>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
